<?php
/**
* Copyright © 2016 Mozg. All rights reserved.
* See LICENSE.txt for license details.
*/

/*
dump($this->getData());
dump(get_class_methods(get_class($this)));
dump(get_class_vars(get_class($this)));

https://codepen.io/whqet/pen/EJgwb

Responsive Checkout Progress Bar

*/

?>

<!-- Responsive Checkout Progress Bar -->
<!-- <?php echo get_class($this) ?> -->

<script type="text/javascript">
console.log('Responsive Checkout Progress Bar');
console.log('<?php echo get_class($this) ?>');
</script>

<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>

<?php echo $this->getStatusHistoryRssUrl($_order) ?>

<?php
//SE STATE NEGATIVO MOSTRAR MENSAGEM
$stateNegative = array('closed','canceled','holded');
if(in_array($_order->getState(), $stateNegative)):
?>
<div class="closed canceled holded">
<?php echo $this->__('Fechado, Cancelado ou Aguardando Aprovação')?>
</div>
<?php else:?>
<div id="statusOrder" class="checkout-wrap">
<ul class="label-bar">
<li class="pending"><?php echo $this->__('Order Created') ?></li>
<li class="pending_payment payment_review"><?php echo $this->__('Payment Authorization') ?></li>
<li class="processing"><?php echo $this->__('Separated Order') ?></li>
<li class="complete_shipped"><?php echo $this->__('Product in Transportation') ?></li>
<li class="complete"><?php echo $this->__('Product Delivered') ?></li>
</ul>
<ul class="checkout-bar">
<li class="pending"></li>
<li class="pending_payment payment_review"></li>
<li class="processing"></li>
<li class="complete_shipped"></li>
<li class="complete"></li>
</ul>
<ul class="label-bar-bottom">
<li class="pending"></li>
<li class="pending_payment payment_review"></li>
<li class="processing"></li>
<li class="complete_shipped"></li>
<li class="complete"></li>
</ul>
</div>
<script type="text/javascript">
//<![CDATA[
jQuery(function ($) {
    $(document).ready(function(){
        var statuslabel = '<?php echo $_order->getStatusLabel() ?>';
        var status      = '<?php echo $_order->getStatus() ?>';
        var data        = '<?php echo $_order->getCreatedAtDate()->toString('d/M/Y H:M') ?>';
        var state       = '<?php echo $_order->getState() ?>';
        var history     = new Object();
        var progress    = '<?php echo $this->__('In progress') ?>';
        var complete    = '<?php echo $this->__('Complete') ?>';
        <?php
        //GERAR ARQUIVO HISTORY PARA CONSULTA
        $x = 0;
        foreach ($_order->getAllStatusHistory() as $commentObj):
        ?>

        history['<?php echo $x ?>'] = {
        'status'         : '<?php echo $commentObj->getStatus() ?>',
        'comment'        : '<?php //echo $commentObj->getData('comment'); ?>',
        'datestatus'     : '<?php echo $this->formatDate($commentObj->getCreatedAt(), 'short', true) ?>',
        }
        <?php $x++ ?>
        <?php
        endforeach;
        ?>

        if(state == 'new'){
            $('#statusOrder .'+state+'').addClass("visited");
            $('#statusOrder .pending_payment').addClass("active");
        }else if(state == 'complete'){
            $('#statusOrder .'+state+'').addClass("visited");
        }else{
            $('#statusOrder .'+state+'').addClass("active");
        }
        $('li.active').prevAll().addClass('visited');
        $('li.visited').prevAll().addClass('visited');

        $('#statusOrder .label-bar-bottom li.active').append(progress);
        $('#statusOrder .label-bar-bottom li.visited').append(complete);

        $('#statusOrder .label-bar-bottom li.new.visited').append('<br/><span>'+data+'</span>');

        var size = Object.keys(history).length;
        var count = 1;

        console.log('status');

        for(var j in history ){

            var status = history[j].status;
            var datestatus = history[j].datestatus;

            console.log(status);

            if(status){
                if ( ('#statusOrder .label-bar-bottom li.'+status+'.visited span') === undefined){
                    $('#statusOrder .label-bar-bottom li.'+status+'.visited').append('<br/><span>'+datestatus+'</span>');
                }else{
                    $('#statusOrder .label-bar-bottom li.'+status+'.visited').html(complete+'<br/><span>'+datestatus+'</span>');
                }

                count++;
            }

        }
    });
});
//]]>
</script>
<?php endif;?>

<!-- / <?php echo get_class($this) ?> -->
